version: '3'
services:
  PgMaskingProxyDB:
    image: postgres
    restart: always
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test_data
    container_name: PgMaskingProxyDB
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql

  proxy:
    build: .
    ports:
    - 20000:20000
    volumes:
    - .:/app/
    depends_on:
    - PgMaskingProxyDB
